model = 'densenet121'
loss = 'cross_entropy'
optimizer = 'adam'
lr = 0.0001
num_epochs = 50
train = False
freeze = False
modelname = 'densenet121_no_freeze'
eval_metric = 'auc'
# freeze = True
# modelname = 'densenet201_freeze'