model = 'densenet121'
loss = 'cross_entropy'
optimizer = 'adam'
lr = 0.0001
num_epochs = 10
train = True
freeze = False
modelname = 'ViT_pretrained'
eval_metric = 'accuracy'
# freeze = True
# modelname = 'densenet201_freeze'